extends: airbnb-base
env:
  node: true
  mocha: true
rules:
  no-console: "off"
  radix: "off"
overrides:
  - files:
    - test/**/*.js
    - gulpfile.js/**/*.js
    rules:
      import/no-extraneous-dependencies: "off"
